### ISSUE TITLE
(v055) dnscrypt no internet/DNS server down for all servers.

### ISSUE THREAD

**Issue by TalOrenshtein** [celzero/rethink-app#1003]
No matter what server I choose and  if/what relay(s) I choose,  I get (almost) instantly no internet error or (less common)  DNS server down error. Sometimes after starting the service it works for like a few second, I can load a page or two on the internet but the this error popped again. Rolled back to 0.54c for now as it works great there.

**Comment by ignoramous** [comment]
I see this too but only with Quad9 servers, CleanBrowsing and AdGuard servers work fine. Unsure what changed as dnscrypt (in fact, all of the DNS code) is virtually untouched in `v055`.

**Comment by Dyras** [comment]
Same here.

Tested with:

DNSCrypt: AdGuard DNS, with or without relays
DoH: Blah DNS, I added it myself
DoH: RethinkDNS Privacy

**Comment by raven9nine** [comment]
Can confirm the Quad9 issue.
I also rolled back to v54c.
Also the autostart bug [#905](https://github.com/celzero/rethink-app/issues/905) still remains in v055 since it started in the 54c update.

**Comment by ignoramous** [comment]
Fixed in https://github.com/celzero/firestack/commit/2974a2fbe539fe70f3ca941e21015123d4175f3b

Quad9 (as known before) has trouble with fragmented UDP. Rethink now avoids sending larger UDP payloads to ALL upstreams.

Will land in `v055a` (in a day or two).

**Comment by TalOrenshtein** [comment]
Hi again, so I noticed I still get this error while trying to use relays. Without relays it seems to work so far.

**Comment by ignoramous** [comment]
Some DNSCrypt severs don't support relays, unfortunately. Quad9 being one of them.

**Comment by TalOrenshtein** [comment]
Emm but it said it worked on v0.54c. Was it a mistake?

**Comment by ignoramous** [comment]
> Emm but it said it worked on v0.54c. Was it a mistake?

Quad9 has never worked with relays, afaik.

**Comment by TalOrenshtein** [comment]
Alright thank you
