### ISSUE TITLE
No DNS with firewall

### ISSUE THREAD

**Issue by Ypot** [celzero/rethink-app#1308]
I can't allow an app to connect through the firewall and use DNS.

I test it, and there are fewer adds blocked with firewall+DNS, than if I am using only the DNS. Here to test:
https://d3ward.github.io/toolz/adblock

**Comment by ignoramous** [comment]
Can you share screenshots of what you mean when you say *DNS + Firewall* works better than *DNS-only* mode at blocking ads (as tested at `https://d3ward.github.io/toolz/adblock`)?

This shouldn't be the case.

**Comment by Ypot** [comment]
Just DNS running image:
![Screenshot_2024-03-25-22-38-06-02_c8cbde12d3521911922be4eee6a05664](https://github.com/celzero/rethink-app/assets/30699014/f0f35049-522f-4bcc-95d7-0929d7e73272)

Results with just DNS running (good):
![Screenshot_2024-03-25-22-39-29-85_0a156e521caef1694fb53a7dad489d44](https://github.com/celzero/rethink-app/assets/30699014/5dbba3f2-8fae-44e7-bb96-874b95322d58)
[d3_adb_25_3_2024 22_38_37.json](https://github.com/celzero/rethink-app/files/14750030/d3_adb_25_3_2024.22_38_37.json)


RethingDNS Firewall settings:
![Screenshot_2024-03-25-22-40-17-54_c8cbde12d3521911922be4eee6a05664](https://github.com/celzero/rethink-app/assets/30699014/401b7e04-484b-4908-b3cb-0494c830a258)

![Screenshot_2024-03-25-22-40-01-93_c8cbde12d3521911922be4eee6a05664](https://github.com/celzero/rethink-app/assets/30699014/ad37b707-a821-48a0-a459-e22f5bd199d2)


Results with DNS+Firewall (not good):
![Screenshot_2024-03-25-22-40-43-51_0a156e521caef1694fb53a7dad489d44](https://github.com/celzero/rethink-app/assets/30699014/72ed1f7b-ae29-43f2-82c0-6ef8855b6a64)

[d3_adb_25_3_2024 22_41_25.json](https://github.com/celzero/rethink-app/files/14750075/d3_adb_25_3_2024.22_41_25.json)

**Comment by ignoramous** [comment]
1. Some of the domains that show up as *allowed* may have been added to per-app rules?
2. Or, if *any* app is set to *Bypass DNS & Firewall*, then most domain blocks are done at *connection* time (that is, by the Firewall) and not *resolution* time (that is, *not* by the DNS).

**Comment by Ypot** [comment]
Hi @ignoramous 


> 1. Some of the domains that show up as _allowed_ may have been added to per-app rules?
No domains manually allowed.

> 
>     2. Or, if _any_ app is set to _Bypass DNS & Firewall_, then most domain blocks are done at _connection_ time (that is, by the Firewall) and not _resolution_ time (that is, _not_ by the DNS).

I am not sure if I understand it.
I have set to bypass some apps, but not the Opera app, which is the browers with which I am testing the website. Is it not possible to add bypass rules to some apps, while others are using the DNS?

**Comment by ignoramous** [comment]
> Is it not possible to add bypass rules to some apps, while others are using the DNS?

It is. But the behaviour is that ALL domains are resolved as the firewall rules for domains will be applied at connection time. That is, *DNS logs* would show that a particular *domain* was *allowed* but may or may not have been blocked at connection time, which should show up in *Network logs*.

**Comment by ignoramous** [comment]
> It says: the app hasn't been installed because of a conflict with a packet

You likely installed the current app on your Android from F-Droid? If so, you'll have to update to the new version from F-Droid. Only Play Store, GitHub, and Website versions are interchangeably updatable with each other.

**Comment by Ypot** [comment]
It's still happening.
If Wireguard hides my IP, ads are not blocked. 
I stop Wireguard and ads are blocked again.

**Comment by ignoramous** [comment]
Are you using WireGuard in *Simple* mode? If so, WireGuard DNS is then responsible for blocking domains.

**Comment by Ypot** [comment]
Yes, I am using simple mode. 
So, is it possible to have better DNS protection of using simple mode?

**Comment by ignoramous** [comment]
>  So, is it possible to have better DNS protection of using simple mode?

Only with *On-device blocklists* (available on [F-Droid](https://f-droid.org/en/packages/com.celzero.bravedns/) and [GitHub](https://github.com/celzero/rethink-app/releases) or [Website](https://rethinkdns.com/download) builds.

**Comment by Ypot** [comment]
Thanks! 

Not very intuitive, but working!
