### ISSUE TITLE
v055d: SecurityException on Android 14 for exported system broadcasts reciever

### ISSUE THREAD

**Issue by mad1mystic** [celzero/rethink-app#1339]
The latest version crashes on Android 14 , using custom ROM. 0.5.5c working fine though. Tried clean install by removing previous version but crashes . hope there is fix ! Thanks for app

**Comment by hussainmohd-a** [comment]
@FID02, Thanks for the bug report, It will be fixed and included in the next release.

**Comment by danieljl** [comment]
@FID02 Thanks for the acknowledgement. Is there any temporary workaround while waiting the next release?

**Comment by danieljl** [comment]
@hussainmohd-a  Thanks for the acknowledgement. Is there any temporary workaround while waiting the next release?

**Comment by ignoramous** [comment]
> @hussainmohd-a Thanks for the acknowledgement. Is there any temporary workaround while waiting the next release?

Not sure, but you could ask in GrapheneOS forums why crash apps deviating away from stock AOSP behaviour? Can't imagine Rethink is the only app that is crashing due to this?

**Comment by fossifly** [comment]
> @hussainmohd-a Thanks for the acknowledgement. Is there any temporary workaround while waiting the next release?

I went back to version 055a for now. For my use cases this is the most stable version. I had the same crash on an Android 14 gsi, on Samsung Stock it didn't crash.

**Comment by cyress** [comment]
Since the title of this issue has been changed and GrapheneOS is explicitly mentioned, I just wanted to point out that the latest version of the app (v0.5.5d) also crashes immediately upon opening on a Pixel 8 Pro running stock Android v14.

**Comment by danieljl** [comment]
The current latest version (v0.5.5d) can't be launched also on Samsung One UI 6.0 and 6.1. It always crashes every time you open the app.

**Comment by FID02** [comment]
Thank you for the quick fix.

It's possible that this was caused by the April 2024 patch update to PixelOS and Android 14 (AP1A.240405.002). PixelOS sends out updates in batches, unless users check for them manually, while GrapheneOS ships them to all their users once it reaches stable channel. Possibly many users of PixelOS has not received the April update yet.

**Comment by hussainmohd-a** [comment]
The issue appears to be caused by the Play Store library. It has been fixed and will be included in the next release. As a temporary workaround, you can use version v055d from the website.

**Comment by ignoramous** [comment]
Fix released in [`v055e`](https://github.com/celzero/rethink-app/releases/tag/v0.5.5e).

**Comment by mad1mystic** [comment]
Unfortunately v0.5.5e still crashes , tried latest version it's still crashing on Android 14! Reverted back to v0.5.5c

**Comment by hussainmohd-a** [comment]
@mad1mystic Hi, can you send us the bug report if possible?

**Comment by ignoramous** [comment]
@FID02 does `v055e` crash for you, too?

**Comment by FID02** [comment]
> @FID02 does `v055e` crash for you, too? If so, will you please share crash logs?

Installed v055e using the apk from GitHub: doesn't crash. 
Uninstalled. 
Installed v055**d** from _GitHub_: doesn't crash
Uninstalled. 
Installed RethinkDNS v055**d** from the _Play_ Store: crashes

v055d is the latest version available to me from the Play Store. I assume there are slight changes between the GitHub and Play releases?

**Comment by mad1mystic** [comment]
> @mad1mystic Hi, if you're technical enough, can you post output from `adb logcat`? We've got Android 14 devices ourselves and do not see any more crashes.

Here is the log 

```
type: crash
osVersion: Redmi/sweet_eea/sweet:13/RKQ1.210614.002/V14.0.9.0.TKFEUXM:user/release-keys
package: com.celzero.bravedns:36
process: com.celzero.bravedns
processUptime: 384 + 50 ms
installer: com.celzero.bravedns

java.lang.IllegalArgumentException: foregroundServiceType 0x00000400 is not a subset of foregroundServiceType attribute 0x40000000 in service element of manifest file
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3074)
	at android.os.Parcel.createException(Parcel.java:3054)
	at android.os.Parcel.readException(Parcel.java:3030)
	at android.os.Parcel.readException(Parcel.java:2972)
	at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:6825)
	at android.app.Service.startForeground(Service.java:862)
	at com.celzero.bravedns.service.BraveVPNService$onStartCommand$1$$ExternalSyntheticApiModelOutline0.m(SourceFile:0)
	at com.celzero.bravedns.service.BraveVPNService$onStartCommand$1.invokeSuspend(Unknown Source:74)
	at com.celzero.bravedns.service.BraveVPNService$onStartCommand$1.invoke(SourceFile:0)
	at com.celzero.bravedns.service.BraveVPNService$onStartCommand$1.invoke(SourceFile:0)
	at com.celzero.bravedns.service.BraveVPNService$ui$1.invokeSuspend(Unknown Source:30)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:11)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:98)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8275)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@cde266, Dispatchers.Main]
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.am.ActiveServices.setServiceForegroundInnerLocked(ActiveServices.java:2064)
	at com.android.server.am.ActiveServices.setServiceForegroundLocked(ActiveServices.java:1690)
	at com.android.server.am.ActivityManagerService.setServiceForeground(ActivityManagerService.java:13397)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:3418)
	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2782)
```

Still crashing for me on Android 14

**Comment by ignoramous** [comment]
> Since the title of this issue has been changed and GrapheneOS is explicitly mentioned, I just wanted to point out that the latest version of the app (v0.5.5d) also crashes immediately upon opening on a Pixel 8 Pro running stock Android v14.

@cyress Looks like Rethink's downstream dependency fails to work on Android 14. It was a miss on our part (mostly because the test/debug flavours don't crash on Android 14, at all). Unsure when `v055e` will be approved by Google (they usually don't over the weekend)... so this version is going to fair *pretty* badly out there (Play Store reviews).

(I've changed the title)

**Comment by ignoramous** [comment]
> v055d is the latest version available to me from the Play Store. I assume there are slight changes between the GitHub and Play releases?

Yep, the Play Store flavour loads Play Store specific libraries by Google which GitHub, Website, and F-Droid versions don't. And these libraries had to be updated which we didn't.

**Comment by hussainmohd-a** [comment]
@mad1mystic We've created a debug version of the app to investigate potential causes of failure. Two APKs have been uploaded for testing:

- [Test_apk_1](https://cfstore.rethinkdns.com/debugapp%2Frethink_debug_36_declare_all.apk)
- [Test_apk_2](https://cfstore.rethinkdns.com/debugapp%2Frethink_debug_36_foreground_exception.apk)

Please download and test both APKs to check if either resolves the issue, uninstall the production build of the app before installing the debug APKs. We would appreciate it if you could also provide us with the logs for further analysis. Thank you for your assistance!

**Comment by FID02** [comment]
For what it's worth, both debug builds open fine for me without crashing.

**Comment by mad1mystic** [comment]
> @mad1mystic We've created a debug version of the app to investigate potential causes of failure. Two APKs have been uploaded for testing:
> 
> * [Test_apk_1](https://cfstore.rethinkdns.com/debugapp%2Frethink_debug_36_declare_all.apk)
> * [Test_apk_2](https://cfstore.rethinkdns.com/debugapp%2Frethink_debug_36_foreground_exception.apk)
> 
> Please download and test both APKs to check if either resolves the issue, uninstall the production build of the app before installing the debug APKs. We would appreciate it if you could also provide us with the logs for further analysis. Thank you for your assistance!

Debug test builds are working so far no crash on initial app opening . Thank you !waiting for final build .

**Comment by hussainmohd-a** [comment]
@mad1mystic, @FID02 Thank you for the update. I've included three more debug builds for thorough testing to ensure readiness for production. Please download and test these builds and share your findings with me. Thank you!. 

- [Test_apk_1](https://cfstore.rethinkdns.com/rethink_36_with_connected.apk)
- [Test_apk_2](https://cfstore.rethinkdns.com/debugapp%2Frethink_36_with_services_filled.apk)
- [Test_apk_3](https://cfstore.rethinkdns.com/debugapp%2Frethink_36_without_connected.apk)

**Comment by mad1mystic** [comment]
> @mad1mystic, @FID02 Thank you for the update. I've included three more debug builds for thorough testing to ensure readiness for production. Please download and test these builds and share your findings with me. Thank you!.
> 
> * [Test_apk_1](https://cfstore.rethinkdns.com/rethink_36_with_connected.apk)
> * [Test_apk_2](https://cfstore.rethinkdns.com/debugapp%2Frethink_36_with_services_filled.apk)
> * [Test_apk_3](https://cfstore.rethinkdns.com/debugapp%2Frethink_36_without_connected.apk)

Ok trying

**Comment by mad1mystic** [comment]
> I believe the URL may be broken. Here are the correct download links for the first APK and an additional APK for testing:
> 
> * [Test_apk_1](https://cfstore.rethinkdns.com/debugapp%2Frethink_36_with_connected.apk)
> * [Test_apk_2](https://cfstore.rethinkdns.com/debugapp%2Frethink_36_without_c.apk)
> 
> Thank you so much for your assistance!

Test apk 1 [with connected ]- is working no crash .
Test apk 2 [ without c ] is crashing on 

Here is log 

```
type: crash
osVersion: Redmi/sweet_eea/sweet:13/RKQ1.210614.002/V14.0.9.0.TKFEUXM:user/release-keys
package: com.celzero.bravedns:36
process: com.celzero.bravedns
processUptime: 1480 + 58 ms
installer: com.celzero.bravedns

android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{c72584b u0 com.celzero.bravedns/.service.BraveVPNService}
	at android.app.ActivityThread.generateForegroundServiceDidNotStartInTimeException(ActivityThread.java:2136)
	at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:2107)
	at android.app.ActivityThread.-$$Nest$mthrowRemoteServiceException(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2401)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8275)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
Caused by: android.app.StackTrace: Last startServiceCommon() call for this service was made here
	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1983)
	at android.app.ContextImpl.startForegroundService(ContextImpl.java:1937)
	at android.content.ContextWrapper.startForegroundService(ContextWrapper.java:830)
	at android.content.ContextWrapper.startForegroundService(ContextWrapper.java:830)
	at androidx.core.content.ContextCompat$Api26Impl.startForegroundService(Unknown Source:0)
	at androidx.core.content.ContextCompat.startForegroundService(Unknown Source:6)
	at com.celzero.bravedns.service.VpnController.start(Unknown Source:31)
	at com.celzero.bravedns.ui.fragment.HomeScreenFragment.startVpnService(Unknown Source:14)
	at com.celzero.bravedns.ui.fragment.HomeScreenFragment.prepareAndStartVpn(Unknown Source:6)
	at com.celzero.bravedns.ui.fragment.HomeScreenFragment.handleMainScreenBtnClickEvent(Unknown Source:47)
	at com.celzero.bravedns.ui.fragment.HomeScreenFragment.initializeClickListeners$lambda$6(Unknown Source:5)
	at com.celzero.bravedns.ui.fragment.HomeScreenFragment.$r8$lambda$eK6GuIQ7-vSriQ9fg_3l7qkR2Dk(SourceFile:0)
	at com.celzero.bravedns.ui.fragment.HomeScreenFragment$$ExternalSyntheticLambda10.onClick(SourceFile:0)
	at android.view.View.performClick(View.java:7658)
	at android.view.View.performClickInternal(View.java:7635)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:30188)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	... 6 more
```

**Comment by hussainmohd-a** [comment]
@mad1mystic Thank you so much for your assistance. Will fix and push to production.

**Comment by mad1mystic** [comment]
> @mad1mystic Thank you so much for your assistance. Will fix and push to production.

Thanks for the app too ! Waiting for release
