### ISSUE TITLE
"No internet" after restart and system dns

### ISSUE THREAD

**Issue by GambaJo** [celzero/rethink-app#1503]
I use RethinkDNS on 2 Samsung devices and I have the same problem on both devices. I choose the option "System DNS". When I restart my devices RethinkDNS show me the status "no internet".

My workaround is, that after a restart I choose the "Rethink DNS" option, then I hit the refresh button (in the upper right corner of the DNS section). Then I choose the "System DNS" option and hit the refresh button again. After this, I have internet access.

It seems to me, like RethinkDNS has problems with System DNS.

![grafik](https://github.com/celzero/rethink-app/assets/1378907/706c9705-1e4b-46d2-b2d6-d9d567c753dc)

**Comment by ignoramous** [comment]
There were problems with *System DNS* in `v055c` up until `v055e`. Can you check *About* UI in Rethink and scroll to the bottom and tell us which version it shows you?

**Comment by GambaJo** [comment]
> There were problems with _System DNS_ in `v055c` up until `v055e`. Can you check _About_ UI in Rethink and scroll to the bottom and tell us which version it shows you?

vv0.5.5m (fdroid)

**Comment by Kamika242** [comment]
I have this problem on 3 different devices today with 3 different versions of Rethink, v055a, v055j and v055m (all F-Droid), home and mobile network. First I thought there is a failure of my internet connection, but here on my Linux laptop everything is fine, directly connected to the Fritzbox with Adguard DNS servers set as default there.
I also tried to switch to system DNS and back to RDNS+ in Rethink on the 3 devices, no solution.
Is it possible that the provider (Vodafone) blocks Rethink now?

**Comment by ignoramous** [comment]
> 3 hours later, the connection is back on all 3 devices. Absolutely don't know, what the problem was.

Usually *DNS Logs*s should show errors when something like this happens. Each entry also shows which upstream resolver was used and whether it worked or not.

**Comment by ignoramous** [comment]
> Then I choose the "System DNS" option and hit the refresh button again. After this, I have internet access.
>
> It seems to me, like RethinkDNS has problems with System DNS.

@GambaJo sorry, I'm confused. If *System DNS* works after you switch to it, how is it a problem with *System DNS*? You mean *Rethink DNS* has problems?

**Comment by GambaJo** [comment]
> If _System DNS_ works after you switch to it, how is it a problem with _System DNS_? You mean _Rethink DNS_ has problems?

Yes. Only WiFi is on, Mobile internet connection is off. I choose the option "System DNS" in Rethink DNS and restart my phone. After it started, Rethink DNS shows me "no internet". 

![grafik](https://github.com/celzero/rethink-app/assets/1378907/2b1a22f3-21aa-48a9-b51b-4cc816c18996)

So I tried another dns option (Rethink DNS) in the Rethink DNS app. Then I have internet connection. When I switch back to the option "System DNS", I have still internet connection.

![grafik](https://github.com/celzero/rethink-app/assets/1378907/13360616-9647-49a0-b073-71b061448b84)

BUT: When I restart my phone (or turn WiFi off an on again), Rethink DNS shows me "no internet" (see first image)

So everytime I restart my phone or turn my wifi off and on, I have to go into the dns setting of Rethink DNS, choose the Rethink DNS option, refresh, then choose the System DNS option and refresh again. Or disable the Rethink DNS app. Otherwise after every restart Rehink DNS cuts my internet connection.

**Comment by ignoramous** [comment]
When you hir this "no internet" issue, what do you see in *DNS Log*? Tap on any of the failing queries and look at the *footer* of the *bottomsheet* that comes up to see if there are any errors logged.

If not, if you're technical enough, set Rethink in *Very verbose* mode (from *Configure* -> *Settings* -> *Log level*) and capture `adb logcat` at the time this issue (when you switch off wifi and turn it back in again but it keeps showing "no internet" and never auto-recovers from it) happens and email it to us?

**Comment by GambaJo** [comment]
> 5\. Notice there is "no internet" and Rethink does _not_ auto-recover unless Rethink is `STOP`/`START` again _or_ _refresh_ icon is tapped.

Refresh is not enough. I have to choose an other dns server (like Rethink DNS) first, refresh, and then go back to System DNS and refresh.

I send you the logs via mail.

I noticed something strange:
I found this blocked entry
![grafik](https://github.com/celzero/rethink-app/assets/1378907/c265454f-d5ce-437e-b11d-0290bdc1653e)

But this app has a baypass
![grafik](https://github.com/celzero/rethink-app/assets/1378907/85337d45-a462-40af-ad17-db24c56f8f76)

This is a web site I tried to open
![grafik](https://github.com/celzero/rethink-app/assets/1378907/f450ac23-50d9-421f-98a8-e91a1da0ac3a)

**Comment by ignoramous** [comment]
From when *System DNS* works after you switch over to another DNS and/or "refresh", can you post a screenshot, please.

Thanks for the logs, I'll take a look and get back.

**Comment by GambaJo** [comment]
> I am interested in the IP address of the resolver (which in the screenshot that you shared above is `system.`

Where can I find this?

I made a crappy video: https://youtu.be/3M4TZyeZ2EI 
It starts with a reboot of my phone (I have to cover it short, because of my PIN). Then I open Rethink DNS. You can see, System DNS is set and there is no internet. Then I choose another DNS Server, refresh, and choose System DNS and refresh -> I have internet connection (can open a website).
Then I restart my phone, try to open the same website, but it only shows the ofline version. Then I open Rethink DNS -> no internet. And I can restart the whole process (another dna, system dns, ...)

**Comment by ignoramous** [comment]
The issue is, the network reports both IPv6 and IPv4 DNS endpoints, but never responds over IPv6. Unexpectedly, the network reports as being single-stack and having just the IPv4 routes.

There were a couple issues why Rethink did not auto-recover:
- Tapping on `Refresh` wasn't emptying out "Protected" IPs like the ones from *System DNS*. 
- Disconfirming failing IPs from DNS53 was erroneous (disconfirms were expecting IPs whereas DNS53 was sending it IP:Port).

(also see linked commits)

> > I am interested in the IP address of the resolver (which in the screenshot that you shared above is system.
> Where can I find this?

In the *bottomsheet* in *DNS Logs*, just below where it shows IP address / "SEND_FAIL" and the like.

**Comment by Keesschilder** [comment]
> When you hit this "no internet" issue, what do you see in _DNS Log_? Tap on any of the failing queries and look at the _footer_ of the _bottomsheet_ that comes up to see if it shows any error msg.
> 
> If not, if you're technical enough, set Rethink in _Very verbose_ mode (from _Configure_ -> _Settings_ -> _Log level_) and capture `adb logcat` at the time this issue (when you switch off wifi and turn it back in again but it keeps showing "no internet" and never auto-recovers from it) happens and email it to us (`mz` at `celzero` dot `com`)?
> 
> In the meanwhile, I'll also try to reproduce this issue on `v055n`. Have I got the steps right?
> 
> 1. Use _System DNS_.
> 2. Put Android on airplane mode.
> 3. Restart.
> 4. Connect to WiFi
> 5. Notice there is "no internet" and Rethink does _not_ auto-recover unless Rethink is `STOP`/`START` again _or_ _refresh_ icon is tapped.

I've a similar issue and mailed you the logcat.

**Comment by GambaJo** [comment]
Hi, I'm currently use Version v0.5.5n and still have this problem.

**Comment by ignoramous** [comment]
`v055o` has completely overhauled how *System DNS* is setup, and so I expected bugs such as these to have been resolved. 

Please do test and let us know if that not what you observe: https://github.com/celzero/rethink-app/releases/tag/v0.5.5o

**Comment by rugk** [comment]
Having the same issue with v0.5.5o
(com.celzero.bravedns). It did not work with the default "rethink dns" so I switched to system dns, but it did not work either.

Notably, the errors still show that connection to rethinkdns.com is contacted, which I don't even want!

Full video: https://streamable.com/gx6r97 

Nothing resolves, so this could be the same as #1503 or #1544 or #2066 though.

Blolada before worked fine.

**Comment by ignoramous** [comment]
You're using Rethink in DNS-only mode, yeah? I just tested and System DNS worked fine for me. I'll leave it like this for a few more hours to see if I can reproduce the problem you're currently seeing.

Alternatively, you may try the [v055q](https://github.com/celzero/rethink-app/releases/tag/v0.5.5q) (which is also a pre-release) version & verify if things then work. Or, wait until alter today/tomorrow for v055r.

**Comment by rugk** [comment]
Upgraded to
vv0.5.5q (fdroid)
gobind@v20250813215032-153f185 (android/arm64@go1.24.5)
22/08/25, 06:51:19


Still does not work. No internet at all. The red message also shows it. Also used a custom dns server in the meantime, also does not work so maybe https://github.com/celzero/rethink-app/issues/1436 is the same root problem / cause.

Android 15, CalyxOS 6.8.21

**Comment by GambaJo** [comment]
I tested vv0.5.5t the last weeks with 2 devices. It seems to work fine. I saw several times, that the connection was lost, but the "reconnetion" worked automaticaly.

**Comment by ignoramous** [comment]
Thanks @GambaJo 

@rugk can you please test with [`v055y`](https://github.com/celzero/rethink-app/releases/tag/v0.5.5y) & see if things work for your specific setup?

**Comment by GambaJo** [comment]
I use v055y for a few days and until now it seems to work.

**Comment by rugk** [comment]
Yeah thanks, seems to work now. (`vv0.5.5y (fdroid)`)

**Comment by ignoramous** [comment]
Thanks for confirming... closing.

(nb: This issue *might* come back in `v055z` as we are bringing back the new DNS routing layer from `v055v` that was turned off in `v055y`; the new routing layer is required to fix behaviour for *Split DNS*, *DNS for bypass*, and *Advanced DNS filtering* scenarios).
