### ISSUE TITLE
v055o: Block connection on VPN doesnt allow reconnecting

### ISSUE THREAD

**Issue by woodknack** [celzero/rethink-app#2021]
On v055o no matter what settings are changed (even with a fresh install) when Block connection on VPN is enabled it is fine and works normally. however when you disconect and reconnect in any way everthing is blocked.

Except for downloading blocklist. This works with loopback enabled and disabled.

This is only fixed by Forgeting the VPN then Setting up a new VPN.

Also it works normally by disabling Block connection on VPN and leaving Always-on VPN enabled.

**Comment by ignoramous** [comment]
Either caused by
- https://github.com/celzero/firestack/issues/171 (I see it on my device pretty regularly, but we don't know how to fix it)
- Or by test code we embarrassingly forgot to remove (Line 1242):

https://github.com/celzero/rethink-app/blob/3e1c71d4929795c4b01eab05053104ff4d7e47d7/app/src/main/java/com/celzero/bravedns/service/BraveVPNService.kt#L1234-L1242

We'll release v055p pretty soon (hopefully, today) to address the second point.

**Comment by ignoramous** [comment]
It turns out we've also hit an AOSP bug with VpnService.setUnderlyingNetworks: https://github.com/celzero/firestack/issues/171

**Comment by ignoramous** [comment]
Please test v055p: https://github.com/celzero/rethink-app/releases/edit/v0.5.5p

On our test devices, this issue was not reproducible with v055p.

**Comment by woodknack** [comment]
This is still not fixed for me. Even after uninstalling and reinstalling the app and not changing any settings. It still shows the same error.

**Comment by ignoramous** [comment]
Will you please see if setting *Configure* -> *Network* -> *Choose IP version* to "Auto" fixes it (and turning ON *Perform connectivity checks* and set it to "Auto")?

**Comment by woodknack** [comment]
I've tried tbe solution and it doesn't fix the problem where you are blocked if you disconnect in any way. However I found that in both 055p and 055o toggling "Block connection on VPN" allows for access after you are blocked.

I was wrong the issue only occurs when turning on and off the vpn itself not wifi

**Comment by woodknack** [comment]
Forgeting the VPN is not nessesary toggling works in 055o as well

**Comment by climbinginceptionbee** [comment]
I'm also experiencing this issue, just updated to v055p and need to toggle block connection setting on and off for connection to function

**Comment by ignoramous** [comment]
> blocked if you disconnect in any way

What do you mean by "disconnect"? Turn off Rethink or turn off wifi+mobile?

> in both 055p and 055o 

v055o has the bug, which we "fixed" in v055p. Do you have "Stall on no network" turned ON in *Configure* -> *Network*?

**Comment by woodknack** [comment]
my mistake it works fine when turning on and off wifi+mobile or airplane mode.

The issue only occurs when turning off rethink through the app, quick settings tile, or changing any of the network settings.

But this is fixed by turning off and on "Block connection on VPN"

I have tried "Stall on no network" turned on and off and it doesnt seem to change.

**Comment by ignoramous** [comment]
Gotcha. We don't know what's going on as the various connectivity issues being reported on `v055o` and `v055p` vary across devices, ROMs, and Android versions... We have added some more workarounds (which may have what you're seeing) in `v055q`, which we'll launch in a few hours from now.

**Comment by ignoramous** [comment]
@woodknack will you please if `v055q` is any better? https://github.com/celzero/rethink-app/releases/tag/v0.5.5q We've put in a best-guess workaround / fix for data stalls.

**Comment by error-reporting** [comment]
> my mistake it works fine when turning on and off wifi+mobile or airplane mode.
> 
> The issue only occurs when turning off rethink through the app, quick settings tile, or changing any of the network settings.
> 
> But this is fixed by turning off and on "Block connection on VPN"
> 
> I have tried "Stall on no network" turned on and off and it doesnt seem to change.

try turning off rethink and force stop rethink then turn it on again if it crash repeat until it started successfully without crash

**Comment by woodknack** [comment]
No luck with v055q. Still results in the same behavior. Tried  both "Stall on no network" and "Choose IP version" on a fresh install with no other changes.

**Comment by woodknack** [comment]
> > my mistake it works fine when turning on and off wifi+mobile or airplane mode.
> > The issue only occurs when turning off rethink through the app, quick settings tile, or changing any of the network settings.
> > But this is fixed by turning off and on "Block connection on VPN"
> > I have tried "Stall on no network" turned on and off and it doesnt seem to change.
> 
> try turning off rethink and force stop rethink then turn it on again if it crash repeat until it started successfully without crash

tried this didnt work out.

**Comment by ignoramous** [comment]
>  Tried both "Stall on no network" and "Choose IP version" 

Keep *Stall on no network* turned OFF.

1. What issue do you see? Can you post a video grab, if you're comfortable?
2. Do you not see any logs in *Configure* -> *Logs* -> *Network* or *DNS* tabs from apps?
3. Are all apps blocked or only some?
4. Does the stall happen if you turn OFF "Block connections without VPN" setting? You may have to restart Rethink once you turn that OFF.

**Comment by woodknack** [comment]
the issue is the same as having "Block connections without VPN" turned on and the vpn turned off(on 055n).
<details><summary>For example brave browser says</summary>

![Image](https://github.com/user-attachments/assets/4ad4af81-b698-450a-983c-f9c10845a33f)
</details>

when I have stall there are no logs in the network tab and only dns queries by cleanbrowsing.org, one.one.one.one, and adguard-dns.io

all apps are blocked except for rethinkdns itself. I tested this when downloading the blocklist. It download when all other apps don't work and doesn't download if I turn off "Use in-app Downloader"

no everything works as intended with "Block connections without VPN" turned off immediately.

**Comment by woodknack** [comment]
rebooting the phone when rethink works as intended with "Block connections without VPN" enabled causes the next boot to boot with stall.

**Comment by StarPicard** [comment]
I have recognized that my DNS server is not used. Normally, I use the DNS server of my router to resolve some internal domains, these are now resolved by an external DNS Server. 

Connectivity first didn't work, but then suddenly worked. I'm on the o release.

**Comment by climbinginceptionbee** [comment]
> the issue is the same as having "Block connections without VPN" turned on and the vpn turned off(on 055n).

I'm also still having the same issue as woodknack

- all apps are blocked
- toggling block connections without VPN immediately fixes it
- I'm able to toggle it back on after any of the blocked apps makes a connection/loads a web page without issue
- does not appear to start logging connection attempts except for rethinks DNS requests
- I currently have the stall connections setting off, IP version set to auto, and connectivity checks set to auto

I'm currently running grapheneos with a Pixel 8 Pro on the latest stable version (A16, 2025080600)

**Comment by bLu02th** [comment]
not sure but I think it is related to the "block any app not in use" setting? turned it off and I was able to reconnect using NextDNS / DoH with the "block connections without vpn" is enabled 😅

**Comment by climbinginceptionbee** [comment]
> not sure but I think it is related to the "block any app not in use" setting? turned it off and I was able to reconnect using NextDNS / DoH with the "block connections without vpn" is enabled 😅

I don't/haven't had that setting enabled, glad its working for you though ☺️

**Comment by DwainZwerg** [comment]
I have since installed q and found that the connectivity issues occur every time you change networks (WiFi to Ethernet, to mobile data, to other WiFi), RethinkDNS loses connectivity and you have to completely set up RethinkDNS again (including deleting all data).

**Android-Version:** ShiftOS-l 7.0 (based on LineageOS 22.2)
**Device:** Shiftphone 8.0 (512 GB)

**Comment by ignoramous** [comment]
> installed q and found that the connectivity issues occur every time you change networks (WiFi to Ethernet, to mobile data, to other WiFi

Do you have *Block connections without VPN* turned ON?

**Comment by DwainZwerg** [comment]
Yes.

**Comment by DwainZwerg** [comment]
But the connection is lost since the moment the network changes.

**Comment by bLu02th** [comment]
> not sure but I think it is related to the "block any app not in use" setting? turned it off and I was able to reconnect using NextDNS / DoH with the "block connections without vpn" is enabled 😅

but i got disconnected again when switching between wifi and mobile data on my tests, apologies for that 😅

**Comment by Alexander-Shukaev** [comment]
> I have since installed q and found that the connectivity issues occur every time you change networks (WiFi to Ethernet, to mobile data, to other WiFi), RethinkDNS loses connectivity and you have to completely set up RethinkDNS again (including deleting all data).
> 
> **Android-Version:** ShiftOS-l 7.0 (based on LineageOS 22.2) **Device:** Shiftphone 8.0 (512 GB)

You don't have to set it up "anew", just force stop it and clear cache...

**Comment by Alexander-Shukaev** [comment]
I've spotted yet another issue though, when connection goes bonkers, I sometimes decide to pause Rethink (used to do this on version n and it always worked), do the work and then unpause it.  In version n that sometimes even fixed the dead wg proxy tunnel.  In latest version (and it started in o), when unpausing, traffic does not go through wg proxy anymore, it flows naked on both DNS and data exposing one completely...  The solution is as per my previous comment.

**Comment by DwainZwerg** [comment]
> You don't have to set it up "anew", just force stop it and clear cache …

For me, that's not enough. I usually have to completely reinstall Rethink (by importing settings via a recovery file), but sometimes deleting data and cache and forcing a stop is suffice.

**Comment by climbinginceptionbee** [comment]
Resolved as of v55r for me! Connection is much snappier too, thank you for your hard work 😊

**Comment by woodknack** [comment]
It Works on 055r. Ive tried rebooting, turning off wifi, airplane mode, and stopping rethink. They all work

**Comment by error-reporting** [comment]
> It Works on 055r. Ive tried rebooting, turning off wifi, airplane mode, and stopping rethink. They all work

is Block connection on VPN turned on when you tested this on 055r?

**Comment by woodknack** [comment]
> > It Works on 055r. Ive tried rebooting, turning off wifi, airplane mode, and stopping rethink. They all work
> 
> is Block connection on VPN turned on when you tested this on 055r?

yes

**Comment by ignoramous** [comment]
Thanks for confirming! Closing...

(if anyone else encounters this on `v055r` or later, feel free to ask to reopen).
