### ISSUE TITLE
v055q: IP leaks with WireGuard

### ISSUE THREAD

**Issue by luciahk1** [celzero/rethink-app#2091]
I'm experiencing clear issues with WireGuard leaking my real IP.

To explain in detail: I'm using a Mullvad WireGuard configuration file as my VPN, with "Always-on VPN" and "Block connections without VPN" toggled on in Android.

1. Real IP Leak When VPN Is Down

If the Mullvad server goes down, my real IP is exposed, and internet access continues as normal. The same thing happens if my Mullvad subscription expires,my internet still works, but my real IP is visible.

Although I have Android’s “Block internet without VPN” setting enabled, Android still considers the VPN active because RethinkDNS is running in VPN mode for firewall purposes. This seems to trick the system into thinking the VPN is on, even when the Mullvad tunnel isn't functioning properly.

2. Brief IP Leak on Connection

On multiple occasions, I’ve checked my IP and initially seen my real IP, only for it to switch to my Mullvad IP after a few seconds. At first, I thought it was a one-time issue, but it keeps happening several times a day. Real IP was revealed from time to time without a specific reason.

Interestingly, this second issue never occurred on the stable version. However, the first issue,where the real IP is exposed when the server is down, did happen on version N.

I understand that point #1 is an edge case, which may explain why it isn’t widely reported. Most users won’t notice it since 99% of the time the WireGuard file is valid and the server is online. But in rare cases, like when the server is down, users might unknowingly use their real IP without any warning.

**Comment by imjuzcy** [comment]
Do you have "Always-On" or "Lockdown" turned on **within the app** (not those in your system settings)?

**Comment by luciahk1** [comment]
Yes, I have always on and lockdown turned on within the app

**Comment by ignoramous** [comment]
> This seems to trick the system into thinking the VPN is on, even when the Mullvad tunnel isn't functioning properly.

As imjuzcy mentions, if you're running WireGuard in *Advanced* mode, then you can mark this WireGuard as *Lockdown* to prevent apps assigned to it from using any other network.

It seems like you already do so, but double-check once.

> On multiple occasions, I’ve checked my IP and initially seen my real IP, only for it to switch to my Mullvad IP after a few seconds

Can you search for the domain/app you're using to check your IP in *Configure* -> *Logs* -> *Network*? The non-proxied connections show up without white-coloured left-hand side border. Tap on those entries and a bottomsheet should come up, which should show additional information about that entry / connection. The top right-hand corner should show a chip with the kind of rule (block/allow/proxy) that was applied to the IP/app/connection.

**Comment by imjuzcy** [comment]
Okay, I've done some testing on my end, and I'm not sure if the issue I face is the same as yours, but I also found some network leaks.

Here is my description of the problem. I used `tcpdump` on my router to sniff the network connections coming from my phone. My phone has Rethink, "Always-on VPN" and "Block connections without VPN" is turned on for Rethink in Android settings, "Lockdown" and "Always-on" enabled for the proxies within Rethink. I have three proxies, and they cover all IP ranges.

But there are still some network connections that went through outside the tunnel, as can be seen on the `tcpdump` logs. For example, IMAPS traffic from Thunderbird. STUN traffic from Syncthing-fork, QUIC traffic from Instagram and Whatsapp, HTTP (not even HTTPS!) traffic from WeChat. This is not even an exhaustive list. There seems to be holes everywhere!

**Comment by ignoramous** [comment]
> For example, IMAPS traffic from Thunderbird. STUN traffic from Syncthing-fork, QUIC traffic from Instagram and Whatsapp, HTTP (not even HTTPS!) traffic from WeChat

As above, will you please if any entries in *Configure* -> *Logs* -> *Network* show up without white-coloured left-hand side border (which indicates that connection using underlying network). Tap on those entries and a bottomsheet with more information should come up. See what it says?

It could be possible that Rethink is not applying rules correctly if it isn't recognising the app correctly:

- #2092

**Comment by imjuzcy** [comment]
It says "No Rule". But weirdly just above it, there is an identical entry with the same destination address, same timestamp, from the same app, but that shows "wg2", which is the correct proxy. The only difference between these two entries are the amount of data sent and received, and the text below.

<details><summary>Here are the screenshots.</summary>

<img width="1080" height="1179" alt="Image" src="https://github.com/user-attachments/assets/d474540d-0bde-4cdf-93b4-903f26b938c2" />
<img width="1080" height="1182" alt="Image" src="https://github.com/user-attachments/assets/c414e0c6-f358-479b-9c7c-1f6e0e80f881" />
</details>

**Comment by imjuzcy** [comment]
I think it warrants at least an optional kill switch feature, so that everything that is not going through any proxy should be dropped.

**Comment by ignoramous** [comment]
Thanks. Sounds like the db bug first reported yesterday: #2092 

Did you do a backup/restore on this version or the previous before (Rethink) update or uninstall apps or uninstall+reinstall any app or update the ROM (after installing `v055o` or later)?

**Comment by ignoramous** [comment]
> kill switch feature, so that everything that is not going through any proxy should be dropped.

This is exactly what *Always-on* + *Lockdown* on a WireGuard in *Advanced* mode or any WireGuard in *Simple* mode is supposed to do (except for apps explicitly marked *Bypass app from all proxies*).

I'm surprised the database is so messed up that this doesn't end up happening. Think we may need more logs from your device to debug this as we haven't hit this ourselves (yet).

**Comment by imjuzcy** [comment]
> Did you do a backup/restore on this version or the previous before (Rethink) update or uninstall apps or uninstall+reinstall any app or update the ROM (after installing v055o or later)?

Nope, everything set up from scratch

**Comment by imjuzcy** [comment]
I have recreated this on an old phone I had, and it seems that the UI is not reliable at telling if things are proxied or not too. On this phone, everything is shown as proxied, but `tcpdump` still show that there are network connections made outside the tunnel.

<details><summary>Here are some screenshots.</summary>

<img width="589" height="623" alt="Image" src="https://github.com/user-attachments/assets/7129ed4c-59c3-46e8-8266-1762d70578b0" />

<img width="1693" height="608" alt="Image" src="https://github.com/user-attachments/assets/60e0d258-c577-4cf4-9fbe-1e14fe9784d9" />
</details>

**Comment by luciahk1** [comment]
There is definitely a leak while on wireguard.
Usually when everything is going with wireguard normally, I see the DNS query (resolved anonymously by .... via..)
However when there is a leak, then nothing is appearing in the log (no DNS query)

**Comment by ignoramous** [comment]
> On this phone, everything is shown as proxied ... tcpdump still show that there are network connections made outside the tunnel

Do you have *Choose IP version* in *Configure* -> *Network* set to *Auto*? If so, is *Perform connectivity checks* turned ON and set to *Auto*? That might explain connections to those IPs.

btw, Rethink has a feature to capture all packets in the tunnel (even if *Network* logs UI won't show them) but not packets sent by Rethink itself (though, you can turn ON *Configure* -> *Network* -> *Loopback* to route Rethink into the same tunnel as other apps... but connectivity checks, if enabled, will still be sent outside the tunnel), and you can enable that from *Configure* -> *Settings* -> *Packet capture*.

**Comment by imjuzcy** [comment]
> Do you have Choose IP version in Configure -> Network set to Auto?

No, it's set to IPv4.

**Comment by imjuzcy** [comment]
I think I found a way to (semi-)reliably recreate it. On this old phone, there are not a lot of apps. 

1. I installed Rethink
2. Set up a WireGuard tunnel, `0.0.0.0/0,::/0` as `AllowedIPs`
3. Turned on "Lockdown" and "Always-on" in Rethink. Other than that, everything in Rethink is as default.
4. Turned on "Always-on" and "Block connections without VPN" in Android settings
5. Install Thunderbird from F-Droid
6. Set up a IMAP email in Thunderbird (I use GMX.de)
7. Then monitor the network activity. 
 
Not always, but sometimes the IMAPS connections don't get proxied. I monitored the network activity from the phone for about an hour, and I found IMAPS from Thunderbird, and some HTTPS activity by Play Service that are not in the WireGuard tunnel. They are shown as "No Rule" in Rethink.

**Comment by imjuzcy** [comment]
Just tested on v055n, there are also leaks there too. So it seems that it's much deeper than just the new versions.

**Comment by doobydooby72** [comment]
> Just tested on v055n, there are also leaks there too. So it seems that it's much deeper than just the new versions.

Might be the network > loopback (experimental) setting I used to get no DNS leaks with my VPN config I think, no fallback dns, DNS > advanced > Prevent DNS leaks (is on by default for me) 55n is the best version imo

**Comment by ignoramous** [comment]
> Not always, but sometimes the IMAPS connections don't get proxied.

How are you saying those connections weren't proxied? By looking at *Configure* -> *Logs* -> *Network*? If so, there's a UI bug when multiple "Always-on" WireGuards are enabled.

If you're monitoring traffic externally (on your router, for example), and it shows Rethink leaking connections to your IMAPS endpoint outside of a *Lockdown* WireGuard, then that's a concern. What does Rethink's *Network* logs tell you in that case?

It'd also help if you can grab logs from *Configure* -> *Settings* -> *App logs*. Tap on the filter icon and set the log level to *Very Verbose*. Note that the log level will switch back to *Error* after ~3 hours (as higher log levels drain battery).

**Comment by imjuzcy** [comment]
> If you're monitoring traffic externally (on your router, for example), and it shows Rethink leaking connections to your IMAPS endpoint outside of a Lockdown WireGuard, then that's a concern. 

Yes, I monitor the network traffic on the router. 

> What does Rethink's Network logs tell you in that case?

It shows "No Rules", even though I have a WireGuard proxy with `0.0.0.0/0` as `AllowedIPs`, and that proxy has Lockdown and Always-on turned on, and  "Always-on VPN" and "Block connections without VPN" is turned on for Rethink in system settings.

> It'd also help if you can grab logs from Configure -> Settings -> App logs. Tap on the filter icon and set the log level to Very Verbose.

I'll do this and let you know.

**Comment by ignoramous** [comment]
> It shows "No Rules", even though I have a WireGuard proxy with 0.0.0.0/0 as AllowedIPs

Hm. Have you observed a pattern in when these leaks happen? For example, only when Rethink starts up anew that the first few packets leak outside of the *Lockdown* + *Always-on* WireGuard?

**Comment by imjuzcy** [comment]
No, there is no pattern that I could tell so far.

**Comment by imjuzcy** [comment]
<details><summary>Here are the logs</summary>

```
1755712659238,E ProxyLogs: err loading wg config: /data/user/0/com.celzero.bravedns/files/wireguard/wg0.conf, invalid config
1755712659238,E ProxyLogs: deleteConfig: wg not found, id: 0, 1
1755712659317,E ProxyLogs: err loading wg config: /data/user/0/com.celzero.bravedns/files/wireguard/wg0.conf, invalid config
1755712659318,E ProxyLogs: deleteConfig: wg not found, id: 0, 1
1755712659413,E ProxyLogs: err loading wg config: /data/user/0/com.celzero.bravedns/files/wireguard/wg1.conf, invalid config
1755712659413,E ProxyLogs: deleteConfig: wg not found, id: 1, 1
1755712659450,E ProxyLogs: err loading wg config: /data/user/0/com.celzero.bravedns/files/wireguard/wg1.conf, invalid config
1755712659450,E ProxyLogs: deleteConfig: wg not found, id: 1, 1
1755712662293,E GoLog: E nic.go:428>nic.go:164>snooper.go:169>nested.go:131>fdbased.go:506: ns: tun(-1): WritePackets (to tun): fd invalid (pkts: 1)
1755712662294,E GoLog: E nic.go:428>nic.go:164>snooper.go:169>nested.go:131>fdbased.go:506: ns: tun(-1): WritePackets (to tun): fd invalid (pkts: 1)
1755712662325,E GoLog: E receive.go:111>wgconn.go:398: wg: bind: wg3 recvFrom(<nil>): 0 / ov? false<=false / err? read udp4 0.0.0.0:42694: use of closed network connection
1755712662326,E GoLog: E receive.go:111>wgconn.go:398: wg: bind: wg3 recvFrom(<nil>): 0 / ov? false<=false / err? read udp6 [::]:42694: use of closed network connection
1755712924968,E GoLog: E receive.go:111>wgconn.go:398: wg: bind: wg3 recvFrom(<nil>): 0 / ov? false<=false / err? read udp4 0.0.0.0:42694: use of closed network connection
1755712924968,E GoLog: E receive.go:111>wgconn.go:398: wg: bind: wg3 recvFrom(<nil>): 0 / ov? false<=false / err? read udp6 [::]:42694: use of closed network connection
1755712926649,E RethinkUI: err submitting data: Job was cancelled
1755712964707,E RethinkUI: err submitting data: Job was cancelled
1755713166979,E GoLog: E receive.go:111>wgconn.go:398: wg: bind: wg3 recvFrom(<nil>): 0 / ov? false<=false / err? read udp4 0.0.0.0:42694: use of closed network connection
1755713166979,E GoLog: E receive.go:111>wgconn.go:398: wg: bind: wg3 recvFrom(<nil>): 0 / ov? false<=false / err? read udp6 [::]:42694: use of closed network connection
1755713531933,E GoLog: E receive.go:111>wgconn.go:398: wg: bind: wg3 recvFrom(<nil>): 0 / ov? false<=false / err? read udp4 0.0.0.0:42694: use of closed network connection
1755713531934,E GoLog: E receive.go:111>wgconn.go:398: wg: bind: wg3 recvFrom(<nil>): 0 / ov? false<=false / err? read udp6 [::]:42694: use of closed network connection
1755713673766,E GoLog: E receive.go:111>wgconn.go:398: wg: bind: wg3 recvFrom(<nil>): 0 / ov? false<=false / err? read udp4 0.0.0.0:42694: use of closed network connection
1755713673767,E GoLog: E receive.go:111>wgconn.go:398: wg: bind: wg3 recvFrom(<nil>): 0 / ov? false<=false / err? read udp6 [::]:42694: use of closed network connection
1755713809634,E GoLog: E common.go:283>common.go:442>cp.go:37>cp.go:68>retrier.go:460: retrier: read: Exit: [192.168.1.185:33678<=142.250.184.227:443]; t: 537ms; b: 0/4096 (tee: 0); err: EOF
1755714039396,E GoLog: E common.go:283>common.go:442>cp.go:37>cp.go:68>retrier.go:460: retrier: read: Exit: [192.168.1.185:42724<=216.239.38.57:443]; t: 541ms; b: 0/4096 (tee: 0); err: EOF
1755714162530,E GoLog: E common.go:283>common.go:442>cp.go:37>cp.go:68>retrier.go:460: retrier: read: Exit: [192.168.1.185:41492<=142.250.186.170:443]; t: 542ms; b: 0/4096 (tee: 0); err: EOF
1755714202547,E GoLog: E common.go:283>common.go:442>cp.go:37>cp.go:68>retrier.go:460: retrier: read: Exit: [192.168.1.185:57042<=142.250.185.138:443]; t: 541ms; b: 0/4096 (tee: 0); err: EOF
1755714242155,E GoLog: E common.go:283>common.go:442>cp.go:37>cp.go:68>retrier.go:460: retrier: read: Exit: [192.168.1.185:57222<=142.250.185.74:443]; t: 537ms; b: 0/4096 (tee: 0); err: EOF
1755714385936,E FirewallManager: no app icon for com.whatsappcom.whatsapp
1755714466882,E FirewallManager: no app icon for com.whatsappcom.whatsapp
1755714469467,E FirewallManager: no app icon for com.whatsappcom.whatsapp
```
</details>

<details><summary>Here is a screenshot of the app</summary>

![Image](https://github.com/user-attachments/assets/bc2793ef-9993-44cb-83fc-beccf54f5869)

</details>

<details><summary>Here is a screenshot of Wireshark sniffing packets from my router</summary>

<img width="2561" height="644" alt="Image" src="https://github.com/user-attachments/assets/aa2ee995-1d8e-4dd5-a41f-81bf927d8cf8" />

</details>

What I did was installed WhatsApp from Google Play, and the uninstalled it. But this is not the only time connections will leak. There are also leaks when I did not install not uninstall anything, just using the phone as normal.

All the 5 IPs in the application log, with EOF errors, are present in the Wireshark as leaked connections.

**Comment by imjuzcy** [comment]
In the previous entry, the change to the log verbosity did not work. So here is a second try.

[Here](https://github.com/user-attachments/files/21905074/log_1755720226377.txt) is the very verbose logs. I removed some of my IPs, the public IPs are still intact. One of the leaked IP is `212.227.17.170` (IMAP server).

**Comment by luciahk1** [comment]
Hi,
With version r, I am not encountering any IP leak so far.
Looks like the issue is resolved

**Comment by imjuzcy** [comment]
I'm testing `v055r` too, so far it seems like it's resolved for me too. But I'll have to test it for a longer time to be sure. I'll report back.

**Comment by imjuzcy** [comment]
I have been monitoring the network for a few hours now, I believe this is resolved too. There are no **IPv4** leaks anymore. 

But I still see some IPv6 traffic outside the tunnel, I still need to check where it's from, since it did not show up in Rethink's log. The connection protocol chosen in Rethink's Settings is IPv4, so I don't know where the connections come from. Nevertheless, I think that should be in another issue.

**Comment by ignoramous** [comment]
> But I still see some IPv6 traffic outside the tunnel

Those could be connectivity checks if you have set up *Configure* -> *Settings* -> *Choose IP version* set to *Auto* and enabled *Perform connectivity checks*.

**Comment by imjuzcy** [comment]
> > But I still see some IPv6 traffic outside the tunnel
> 
> Those could be connectivity checks if you have set up _Configure_ -> _Settings_ -> _Choose IP version_ set to _Auto_ and enabled _Perform connectivity checks_.

IP version is set to IPv4 only

**Comment by ignoramous** [comment]
> version is set to IPv4 only

In that case, it could Android's connectivity checks which bypass VPNs (even in "Block connections without VPN" aka *VPN Lockdown* mode). Ideally these checks are sent to either OEM-owned IPs (like in Samsung phones) or ROM-owned IPs (like with Graphene) or Google IPs (default).

**Comment by imjuzcy** [comment]
Yea, they are all Google's IPs. So I think this issue can be closed. These calls are also present in the official WireGuard app.

One last note, I see a network request from `10.111.222.1` to a Google IP. Is this to be expected? This request is intercepted on the router. Should it be masqueraded to the device's IP before coming out?

<details><summary>Here is a screenshot of it</summary>

<img width="1869" height="22" alt="Image" src="https://github.com/user-attachments/assets/bd6caf15-6c26-4105-8153-f9ec2a776720" />

</details>

**Comment by ignoramous** [comment]
> One last note, I see a network request from 10.111.222.1 to a Google IP.

It could be either Rethink's use of Google DNS for app update checks or blocklist downloads (today, Rethink uses one among Google DNS or Quad9 or Cloudflare DNS) or Rethink's calling into Google Play Framework libraries (which shouldn't be the case for F-Droid and Website/GitHub builds).

It could also be that *Configure* -> *Network* -> *Choose Fallback DNS* is set to "Google" or "System" (and *System DNS* is set to Google's public DNS).

Other than that, apps may also be contacting any of the Google IPs on their own or calling into Google Play Framework.
