### ISSUE TITLE
v055u: wifi only automation not always working

### ISSUE THREAD

**Issue by shifoc** [celzero/rethink-app#2354]
It stays paused

**Comment by ignoramous** [comment]
On some WiFi networks, the actual SSIDs remain "hidden".

Will you filter for `getNetworkSSID` in *Configure -> Settings -> App logs* (remember to change the log level to "Very verbose" by tapping on the filter icon in the search bar of the *App logs* UI) as you switch to WiFi where the WireGuard stays *paused* when it shouldn't? That should tell us whether the active WiFi network is hiding its SSID.

**Comment by shifoc** [comment]
> On some WiFi networks, the actual SSIDs remain "hidden".
> 
> Will you filter for `getNetworkSSID` in *Configure -> Settings -> App logs* (remember to change the log level to "Very verbose" by tapping on the filter icon in the search bar of the *App logs* UI) as you switch to WiFi where the WireGuard stays *paused* when it shouldn't? That should tell us whether the active WiFi network is hiding its SSID.

I couldn't see anything in the logs but if I stop the service and start it again it will connect instantly

**Comment by ignoramous** [comment]
>  start it again it will connect instantly

Wow. Strange. 

> I couldn't see anything in the logs 

At "Very verbose" log level, Rethink should print logs with `getNetworkSSID` in it, which the search filter should be able to reveal. To make sure the search filter isn't struggling (due to a high volume of "Very verbose" logs streaming in), you can set the log level back to "None" to pause log collection before you use search.

**Comment by shifoc** [comment]
Hi again,

I am not sure but I think if the app is in the background, it doesn't work.

```
1762503214588,V ConnectivityEvents: getNetworkSSID: SSID is unknown for network 716370268173, falling back to WifiManager
...
1762503214687,V ConnectivityEvents: isNetworkCellular: netid: 166, hasCellular? false, hasWifi? true, metered? false
...
v4: [NetworkProperties(network=166, capabilities=[ Transports: WIFI Capabilities: NOT_METERED&INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VPN&VALIDATED&NOT_ROAMING&FOREGROUND&NOT_CONGESTED&NOT_SUSPENDED&NOT_VCN_MANAGED&NOT_BANDWIDTH_CONSTRAINED LinkUpBandwidth>=16143Kbps LinkDnBandwidth>=44260Kbps TransportInfo: <SSID: <unknown ssid>, BSSID: 02:00:00:00:00:00, MAC: 02:00:00:00:00:00, IP: /***, Security type: 3, Supplicant state: COMPLETED, Wi-Fi standard: 11ax, RSSI: -40, Link speed: 573Mbps, Tx Link speed: 573Mbps, Max Supported Tx Link speed: 573Mbps, Rx Link speed: 573Mbps, Max Supported Rx Link speed: 573Mbps, Frequency: 5200MHz, Net ID: -1, Metered hint: false, score: 60, isUsable: true, CarrierMerged: false, SubscriptionId: -1, IsPrimary: -1, Trusted: true, Restricted: false, Ephemeral: false, OEM paid: false, OEM private: false, OSU AP: false, FQDN: <none>, Provider friendly name: <none>, Requesting package name: <none><none>MLO Information: , Is TID-To-Link negotiation supported by the AP: false, AP MLD Address: <none>, AP MLO Link Id: <none>, AP MLO Affiliated links: <none>, Vendor Data: <none>> SignalStrength: -40 UnderlyingNetworks: Null], linkProperties={InterfaceName: wlan0 
...
1762503214692,D RethinkDnsVpn: VpnService; getNetworkSSID - onNetworkConnected: active: null, v4: 716370268173##, v6:
```

when the app was in foreground I got those logs:
```
1762502544792,I ConnectivityEvents: getNetworkSSID: SSID for network 441492361229 is: <Redacted>
```

is it because you are missing the ACCESS_BACKGROUND_LOCATION permission to get the SSID info while in background?

**Comment by ignoramous** [comment]
Perhaps! 

```diff
+ <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
+ <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
+ <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
+ <uses-permission android:name="android.permission.ACCESS_BACKGROUND_LOCATION" tools:targetApi="29" />
+ <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
```

Pointers: https://github.com/wgtunnel/wgtunnel/commit/7f0fea3766a4d807bfa0b7801fd6a1ffc88ec7b1

Surprising since all VPNs are technically registered as being in *foreground* 🤷

**Comment by ignoramous** [comment]
Should be fixed in [`v055v`](https://github.com/celzero/rethink-app/releases/tag/v0.5.5v). Please test and let us know if that's not the case. 

Closing... feel free to reopen. Thanks.

**Comment by shifoc** [comment]
> Should be fixed in [`v055v`](https://github.com/celzero/rethink-app/releases/tag/v0.5.5v). Please test and let us know if that's not the case. 
> 
> Closing... feel free to reopen. Thanks.

Hi,

It's not fixed,
It connects to the proxy even if the wifi doesn't match the condition now. 

also I don't have permission to reopen the issue @ignoramous

**Comment by ignoramous** [comment]
@hussainmohd-a please test this. I thought we had fixed the issues wrt WireGuard automation, but apparently not.

I did a test run with the WiFi-only setting and it doesn't work at all.

**Comment by ignoramous** [comment]
[`v055w`](https://github.com/celzero/rethink-app/releases/tag/v0.5.5w) has fixed WiFi-only and Mobile-only automation modes for me. If *both* WiFi-only and Mobile-only automation are turned ON, the resulting behaviour is unexpected: https://github.com/celzero/rethink-app/issues/2758

**Comment by ignoramous** [comment]
@shifoc I tested [`v055x`](https://github.com/celzero/rethink-app/releases/tag/v0.5.5x) and it has fixed issues reported here with network driven WireGuard *Automation*. If you do get the time, do let me know if that holds in your tests. Thanks.

**Comment by shifoc** [comment]
> @shifoc I tested [`v055x`](https://github.com/celzero/rethink-app/releases/tag/v0.5.5x) and it has fixed issues reported here with network driven WireGuard *Automation*. If you do get the time, do let me know if that holds in your tests. Thanks.

Hello,

Bug is still present

**Comment by shifoc** [comment]
@ignoramous https://github.com/user-attachments/assets/f8eb4c51-2060-4547-b46b-3abc997bed37

**Comment by ignoramous** [comment]
WiFi-only and Mobile-only won't turn on an inactive WireGuard.

And, it might take a few seconds for the routes to be setup to WiFi-only / Mobile-only WireGuards.

Mainstream browsers like Firefox and Chrome may reuse pre-established connections, and so the IP changes won't reflect when that happens.

---

For your use case, with the above in mind, how do we reproduce it on our end? Add a rule that matches some SSID *exactly* but doesn't connect (even if active)?

**Comment by shifoc** [comment]
Just to clarify: the original issue I reported was that WiFi-only automation did not connect when the current WiFi matched the configured SSID.

I have not retested that original case yet on v055x.

The issue I am seeing now is different: when I set a specific WiFi SSID in the rule, then connect to another WiFi network with a different SSID, WireGuard still connects/routes anyway.

I have waited 2 mins and it is still connected to wireguard.

So the current repro is:

1. Set WiFi-only automation to match SSID `[configured SSID]`.
2. Connect the device to a different WiFi SSID.
3. WireGuard still connects/routes, even though the SSID does not match.

**Comment by hussainmohd-a** [comment]
Latest (`v056`) should fix this issue. @shifoc Could you please confirm if this is fixed?
