### ISSUE TITLE
CPBL: Final list displays incorrectly in log view 

### ISSUE THREAD

**Issue by slcw** [celzero/rethink-app#362]
Re: v21.08(30) BL update

Queries blocked by "Combined Privacy Block Lists: Final (bongochong)" are attributed to "Dummy Label" with the catagory of "Header" when examining the blocked query in the log view.

![Screenshot_20210831-040344_RethinkDNS-02](https://user-images.githubusercontent.com/87735441/131484775-a0643c6e-33e3-4c17-bca0-b8b6e230097a.jpeg)

**Comment by ignoramous** [comment]
Heh, we ran a manual re-drive of the blocklist updates today, and looks like engs have been fiddling with things they shouldn't normally be. Taking a look...

**Comment by slcw** [comment]
It's more of annoyance than anything, so probably not a high-priority fix.

**Comment by ignoramous** [comment]
Thanks for your bugrepot :)  Fixed in the latest blocklists release. Try a update / re-download (blocklist version remains unchanged).

![Screenshot_20210901-134824~2](https://user-images.githubusercontent.com/852289/131637854-8840d8a0-5d8b-4a19-a764-04b12971179a.jpg)

**Comment by slcw** [comment]
I reset and re-downloaded my blocklists, and the problem remains unchanged. Queries blocked by "CPBL: Final" are still being attributed to "Dummy Label" with the catagory "Header".

**Comment by ignoramous** [comment]
Surprising. Can you please check if that issue is fixed in the beta build `v053f` (only downloadable from the website): [rethinkdns.com/downloads](https://rethinkdns.com/downloads)?

**Comment by slcw** [comment]
Installation of v053f seems to have fixed this problem, and also Issue #363, although I haven't yet tested every blocklist.

Two observations re: v053f
1. The new layout where you have to click to open a window that shows the blocklists that are blocking a particular query is inelegant, and clunky. It was much better when the lists were displayed directly on the query details.
2. Just as you now have a toggle to block each log entry, there should also be a toggle to whitelist the host. We gotta get that whitelisting functionality, and a second toggle on the query details screen would be perfect.

I'm going to do a more thorough test of my blocklists this afternoon, and will update you as needed.

**Comment by ignoramous** [comment]
Thanks.

> The new layout where you have to click to open a window that shows the blocklists that are blocking a particular query is inelegant, and clunky. It was much better when the lists were displayed directly on the query details.

This is a stop-gap (which I thought was in-line with UI of the _Network Logs_ screen), we need to figure out a better way to show blocklists and let users disable / enable them right there on that screen; but UI changes are likely to take a back seat considering we've been wanting forever to integrate WireGuard and fix other issues relating to the network engine. Lets see.

> Just as you now have a toggle to block each log entry, there should also be a toggle to whitelist the host. We gotta get that whitelisting functionality, and a second toggle on the query details screen would be perfect.

This is planned for `v054`. We intend to ship `v054` within 2 to 3 weeks of releasing `v053g` (which is up next; may be this week, may be next). 

> I'm going to do a more thorough test of my blocklists this afternoon, and will update you as needed.

Sure, but `v053f` is a beta-quality release. We've refactored a bunch of things (#282 #354) which has broken _some_ things (like #357 for ex), but fixed a tonne of other bugs (like #277).

**Comment by slcw** [comment]
After monitoring a few hours of traffic, all the lists are working properly and the app is running like a well-oiled machine. The new lists (CPBL and Blocklist Project lists) are a great addition.

**Comment by ignoramous** [comment]
Glad. More improvements incoming. I am closing this issue (and the other one). Feel free to re-open if you think these were not sufficiently addressed. Thanks again for your patience and feedback. Appreciate it.
