### ISSUE TITLE
Retain rules even for uninstalled apps

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#978]
> I'm struggling with the related however, opposite trouble. I wish to keep the settings for apps
> I temporary delete. But the probelm is that once I delete an app, it's Rethink setting gets removed, so I have to set everything up again and again on next installs.
> 
> Can we think of a feature to allow keeping settings for deleted apps?
> 
> Should I create a separate issue for that? (Wanted to start with the easier way discussing it here, and maybe move on in a separate issue).

_Originally posted by @GEkuL in https://github.com/celzero/rethink-app/issues/951#issuecomment-1646870963_

---

more from #951:

> > For removed apps, it would be nice if their rules etc. were persisted in a way that they could still be tidied up later -- perhaps an "Uninstalled apps" screen listing by application ID, where either individual or all app data can be removed?
>
> > Retaining the rules for a large period of time can be my use-case, as I change a country and removing apps non relevant in the current one. But once I get back, I'll need those apps and the privacy set up already configured for them.

**Comment by nightznero** [comment]
Any news in dat case bout implementation? 🙏🏼
Import/Export setting is (not usuless buuut..) so annoying 😩 When import a file and then install app (that was prev saved) is pain. Setting up all those Meta(grr) apps,browsers,MS,Google. And again u have to import files to cover all apps 🥲

**Comment by ignoramous** [comment]
We've implemented this for uninstalled apps (if you reinstall them within 3 to 7 days I think, the previous rules should show up), but I think some more changes are needed for the backup / restore scenario.

**Comment by rcchan** [comment]
Can we please make this configurable beyond 7d / indefinite?

This is an improvement but doesn't solve OPs issue. I also have the same underlying issue because I disable apps that I'm not using (without uninstalling, but it doesn't show up in the app list) and the meticulously defined settings are lost when I need to use the app again.

A related issue is that an app that was intentionally isolated is silently returned to default settings (which, by default unless  the user chooses to isolate all apps, is allow all)

**Comment by ignoramous** [comment]
Implemented in `v055t` with various bugs and I think `v055y` has a stable implementation of this feature in *Configure -> Settings -> Remember uninstalled apps* (or so we think).

**Comment by nightznero** [comment]
> Implemented in `v055t` with various bugs and I think `v055y` has a stable implementation of this feature in *Configure -> Settings -> Remember uninstalled apps* (or so we think).

V055y, I uninstalled app and right after installed again and i wouldn't say its stable. Its doesn't work stable nor for 7days or even 3days, because right after reinstall some app all rules for this app is gone. Its need to be re-open and investigate further

**Comment by hussainmohd-a** [comment]
> > Implemented in `v055t` with various bugs and I think `v055y` has a stable implementation of this feature in *Configure -> Settings -> Remember uninstalled apps* (or so we think).
> 
> V055y, I uninstalled app and right after installed again and i wouldn't say its stable. Its doesn't work stable nor for 7days or even 3days, because right after reinstall some app all rules for this app is gone. Its need to be re-open and investigate further

To understand the issue better, could you please clarify the following?

- Is this happening for all apps that are uninstalled and then reinstalled, or only for specific apps? Are the firewall rules not being retained after reinstallation?
- Are the uninstall and reinstall actions being performed in the main profile?
- If possible, could you share a few screenshots or any additional details? That would help us narrow down the root cause.

**Comment by nightznero** [comment]
https://github.com/user-attachments/assets/593576e8-6cc3-4a44-90cd-5a432891a19f

> > > Implemented in `v055t` with various bugs and I think `v055y` has a stable implementation of this feature in _Configure -> Settings -> Remember uninstalled apps_ (or so we think).
> > 
> > 
> > V055y, I uninstalled app and right after installed again and i wouldn't say its stable. Its doesn't work stable nor for 7days or even 3days, because right after reinstall some app all rules for this app is gone. Its need to be re-open and investigate further
> 
> To understand the issue better, could you please clarify the following?
> 
> * Is this happening for all apps that are uninstalled and then reinstalled, or only for specific apps? Are the firewall rules not being retained after reinstallation?
> * Are the uninstall and reinstall actions being performed in the main profile?
> * If possible, could you share a few screenshots or any additional details? That would help us narrow down the root cause.

Its main profile and also about apps.. its not for all bcs for facebook its held rules

**Comment by Onxr** [comment]
Here's my experience. (V056)

I was using Morphe to patch some apps. I don't think package name was changed. Previously I was using pre patched release from [FiorenMas](https://github.com/FiorenMas/Revanced-And-Revanced-Extended-Non-Root) and recently switched to [NullCpy](https://github.com/nullcpy/rvb)

During migration I had to reinstall and Rethink was showing old entry too. IDK why shouldn't it already detect it's the same app ? How does Rethink detect an app I thought it was based on package name. 
So I had to configure again everything one by one and after 7 days all those old config disappeared.

Currently I'm using a Samsung phone and I manage everything there, then export a backup and using Syncthing-Fork I synced to all other devices of my family and import. The issue is I want to block certain apps that's available in other brand (Xiaomi, Realme) but as you can see rethink forgets if the app isn't present (after 7 days).

What I wanted to do is create a backup on my device then import in other and on that device I'll configure OEM specific apps. Repeat this step for any other device when I'm finished with the last device I'll import the backup on mine and from now on I want everything to be saved even if the app isn't installed so I can use my device to config and import on other devices and still have preconfigured for OEM specific apps of other devices.

I highly request for it.

**Comment by Terrance** [comment]
> I was using Morphe to patch some apps.

As I understand it, the current implementation matches on a combination of package name (e.g. `com.example.app`) and signing key.  As you're patching an app, it's likely re-signed locally and therefore seen as a different app.

**Comment by nightznero** [comment]
> signing key. As you're patching an app, it's likely re-signed locally and therefore seen as a different app.

RethinkDNS checks the singing keys? 
<img width="1080" height="992" alt="Image" src="https://github.com/user-attachments/assets/a5a45135-c2bc-42ff-a7fb-2f3527de5cc5" />
It may be. Then mine screen should have more sense but curious why RethinkDNS doesn't just match package names,but also singing keys.

**Comment by Onxr** [comment]
> > I was using Morphe to patch some apps.
> 
> As I understand it, the current implementation matches on a combination of package name (e.g. `com.example.app`) and signing key. As you're patching an app, it's likely re-signed locally and therefore seen as a different app.

Yep the key was definitely changed. 

> but curious why RethinkDNS doesn't just match package names,but also singing keys.

Same question
